name: hy2-app
services:
  - name: hy2-service
    build:
      dockerfile: Dockerfile
    ports:
      - port: 80
        http:
          paths:
            - path: /
    scaling:
      min: 1
      max: 1
